<template>
  <div>
    <v-row>
      <v-select
        :items="options.opt_sido"
        v-model="support.home_sido"
        label="시도"
        dense
        outlined
        class="ma-2"
      ></v-select>
      <v-select
        :items="filteredData"
        v-model="items.home_id"
        label="구군"
        dense
        outlined
        class="ma-2"
      ></v-select>
      <v-select
        v-model="type"
        :items="kind"
        label="축종"
        dense
        outlined
        class="ma-2"
      ></v-select>
      <v-select label="상세 품종" dense outlined class="ma-2"></v-select>
      <v-select label="상태" dense outlined class="ma-2"></v-select>
    </v-row>
  </div>
</template>

<script>
export default {
  data: () => ({
    items: {
      home_id: null,
    },
    support: {
      home_sido: '',
    },
    options: {
      opt_sido: [
      { text: "서울특별시", value: 1 },
      { text: "부산광역시", value: 2 },
      { text: "대구광역시", value: 3 },
      { text: "인천광역시", value: 4 },
      { text: "광주광역시", value: 5 },
      { text: "세종특별자치시", value: 6 },
      { text: "대전광역시", value: 7 },
      { text: "울산광역시", value: 8 },
      { text: "경기도", value: 9 },
      { text: "강원도", value: 10 },
      { text: "충청북도", value: 11 },
      { text: "충청남도", value: 12 },
      { text: "전라북도", value: 13 },
      { text: "전라남도", value: 14 },
      { text: "경상북도", value: 15 },
      { text: "경상남도", value: 16 },
      { text: "제주특별자치도", value: 17 },
      ],
    opt_gugun: [
      { text: "전체", dependency: 1 },
      { text: "강남구", dependency: 1 },
      { text: "강동구", dependency: 1 },
      { text: "강북구", dependency: 1 },
      { text: "강서구", dependency: 1 },
      { text: "관악구", dependency: 1 },
      { text: "광진구", dependency: 1 },
      { text: "구로구", dependency: 1 },
      { text: "금천구", dependency: 1 },
      { text: "노원구", dependency: 1 },
      { text: "도봉구", dependency: 1 },
      { text: "동대문구", dependency: 1 },
      { text: "동작구", dependency: 1 },
      { text: "마포구", dependency: 1 },
      { text: "서대문구", dependency: 1 },
      { text: "서울특별시", dependency: 1 },
      { text: "서초구", dependency: 1 },
      { text: "성동구", dependency: 1 },
      { text: "성북구", dependency: 1 },
      { text: "송파구", dependency: 1 },
      { text: "양천구", dependency: 1 },
      { text: "영등포구", dependency: 1 },
      { text: "용산구", dependency: 1 },
      { text: "은평구", dependency: 1 },
      { text: "종로구", dependency: 1 },
      { text: "중구", dependency: 1 },
      { text: "중랑구", dependency: 1 },
      { text: "전체", dependency: 2 },
      { text: "강서구", dependency: 2 },
      { text: "금정구", dependency: 2 },
      { text: "기장군", dependency: 2 },
      { text: "남구", dependency: 2 },
      { text: "동구", dependency: 2 },
      { text: "동래구", dependency: 2 },
      { text: "부산진구", dependency: 2 },
      { text: "북구", dependency: 2 },
      { text: "사상구", dependency: 2 },
      { text: "사하구", dependency: 2 },
      { text: "서구", dependency: 2 },
      { text: "수영구", dependency: 2 },
      { text: "연제구", dependency: 2 },
      { text: "영도구", dependency: 2 },
      { text: "중구", dependency: 2 },
      { text: "해운대구", dependency: 2 },
      { text: "전체", dependency: 3 },
      { text: "남구", dependency: 3 },
      { text: "달서구", dependency: 3 },
      { text: "달성군", dependency: 3 },
      { text: "동구", dependency: 3 },
      { text: "북구", dependency: 3 },
      { text: "서구", dependency: 3 },
      { text: "수성구", dependency: 3 },
      { text: "중구", dependency: 3 },
      { text: "전체", dependency: 4 },
      { text: "강화군", dependency: 4 },
      { text: "계양구", dependency: 4 },
      { text: "남동구", dependency: 4 },
      { text: "동구", dependency: 4 },
      { text: "미추홀구", dependency: 4 },
      { text: "부평구", dependency: 4 },
      { text: "서구", dependency: 4 },
      { text: "연수구", dependency: 4 },
      { text: "옹진군", dependency: 4 },
      { text: "중구", dependency: 4 },
      { text: "전체", dependency: 5 },
      { text: "광산구", dependency: 5 },
      { text: "남구", dependency: 5 },
      { text: "동구", dependency: 5 },
      { text: "북구", dependency: 5 },
      { text: "서구", dependency: 5 },
      { text: "전체", dependency: 6 },
      { text: "전체", dependency: 7 },
      { text: "대덕구", dependency: 7 },
      { text: "동구", dependency: 7 },
      { text: "서구", dependency: 7 },
      { text: "유성구", dependency: 7 },
      { text: "중구", dependency: 7 },
      { text: "전체", dependency: 8 },
      { text: "남구", dependency: 8 },
      { text: "동구", dependency: 8 },
      { text: "북구", dependency: 8 },
      { text: "울주군", dependency: 8 },
      { text: "중구", dependency: 8 },
      { text: "전체", dependency: 9 },
      { text: "가평군", dependency: 9 },
      { text: "고양시", dependency: 9 },
      { text: "과천시", dependency: 9 },
      { text: "광명시", dependency: 9 },
      { text: "광주시", dependency: 9 },
      { text: "구리시", dependency: 9 },
      { text: "군포시", dependency: 9 },
      { text: "김포시", dependency: 9 },
      { text: "남양주시", dependency: 9 },
      { text: "동두천시", dependency: 9 },
      { text: "부천시", dependency: 9 },
      { text: "성남시", dependency: 9 },
      { text: "수원시", dependency: 9 },
      { text: "시흥시", dependency: 9 },
      { text: "안산시", dependency: 9 },
      { text: "안성시", dependency: 9 },
      { text: "안양시", dependency: 9 },
      { text: "양주시", dependency: 9 },
      { text: "양평군", dependency: 9 },
      { text: "여주시", dependency: 9 },
      { text: "연천군", dependency: 9 },
      { text: "오산시", dependency: 9 },
      { text: "용인시", dependency: 9 },
      { text: "용인시 기흥구", dependency: 9 },
      { text: "의왕시", dependency: 9 },
      { text: "의정부시", dependency: 9 },
      { text: "이천시", dependency: 9 },
      { text: "파주시", dependency: 9 },
      { text: "평택시", dependency: 9 },
      { text: "포천시", dependency: 9 },
      { text: "하남시", dependency: 9 },
      { text: "화성시", dependency: 9 },
      { text: "전체", dependency: 10 },
      { text: "강릉시", dependency: 10 },
      { text: "고성군", dependency: 10 },
      { text: "동해시", dependency: 10 },
      { text: "삼척시", dependency: 10 },
      { text: "속초시", dependency: 10 },
      { text: "양구군", dependency: 10 },
      { text: "양양군", dependency: 10 },
      { text: "영월군", dependency: 10 },
      { text: "원주시", dependency: 10 },
      { text: "인제군", dependency: 10 },
      { text: "정선군", dependency: 10 },
      { text: "철원군", dependency: 10 },
      { text: "춘천시", dependency: 10 },
      { text: "태백시", dependency: 10 },
      { text: "평창군", dependency: 10 },
      { text: "홍천군", dependency: 10 },
      { text: "화천군", dependency: 10 },
      { text: "횡성군", dependency: 10 },
      { text: "전체", dependency: 11 },
      { text: "괴산군", dependency: 11 },
      { text: "단양군", dependency: 11 },
      { text: "보은군", dependency: 11 },
      { text: "영동군", dependency: 11 },
      { text: "옥천군", dependency: 11 },
      { text: "음성군", dependency: 11 },
      { text: "제천시", dependency: 11 },
      { text: "증평군", dependency: 11 },
      { text: "진천군", dependency: 11 },
      { text: "청주시", dependency: 11 },
      { text: "충주시", dependency: 11 },
      { text: "전체", dependency: 12 },
      { text: "계룡시", dependency: 12 },
      { text: "공주시", dependency: 12 },
      { text: "금산군", dependency: 12 },
      { text: "논산시", dependency: 12 },
      { text: "당진시", dependency: 12 },
      { text: "보령시", dependency: 12 },
      { text: "부여군", dependency: 12 },
      { text: "서산시", dependency: 12 },
      { text: "서천군", dependency: 12 },
      { text: "아산시", dependency: 12 },
      { text: "연기군", dependency: 12 },
      { text: "예산군", dependency: 12 },
      { text: "천안시", dependency: 12 },
      { text: "청양군", dependency: 12 },
      { text: "태안군", dependency: 12 },
      { text: "홍성군", dependency: 12 },
      { text: "전체", dependency: 13 },
      { text: "고창군", dependency: 13 },
      { text: "군산시", dependency: 13 },
      { text: "김제시", dependency: 13 },
      { text: "남원시", dependency: 13 },
      { text: "무주군", dependency: 13 },
      { text: "부안군", dependency: 13 },
      { text: "순창군", dependency: 13 },
      { text: "완주군", dependency: 13 },
      { text: "익산시", dependency: 13 },
      { text: "임실군", dependency: 13 },
      { text: "장수군", dependency: 13 },
      { text: "전주시", dependency: 13 },
      { text: "정읍시", dependency: 13 },
      { text: "진안군", dependency: 13 },
      { text: "전체", dependency: 14 },
      { text: "강진군", dependency: 14 },
      { text: "고흥군", dependency: 14 },
      { text: "곡성군", dependency: 14 },
      { text: "광양시", dependency: 14 },
      { text: "구례군", dependency: 14 },
      { text: "나주시", dependency: 14 },
      { text: "담양군", dependency: 14 },
      { text: "목포시", dependency: 14 },
      { text: "무안군", dependency: 14 },
      { text: "보성군", dependency: 14 },
      { text: "순천시", dependency: 14 },
      { text: "신안군", dependency: 14 },
      { text: "여수시", dependency: 14 },
      { text: "영광군", dependency: 14 },
      { text: "영암군", dependency: 14 },
      { text: "완도군", dependency: 14 },
      { text: "장성군", dependency: 14 },
      { text: "장흥군", dependency: 14 },
      { text: "진도군", dependency: 14 },
      { text: "함평군", dependency: 14 },
      { text: "해남군", dependency: 14 },
      { text: "화순군", dependency: 14 },
      { text: "전체", dependency: 15 },
      { text: "경산시", dependency: 15 },
      { text: "경주시", dependency: 15 },
      { text: "고령군", dependency: 15 },
      { text: "구미시", dependency: 15 },
      { text: "군위군", dependency: 15 },
      { text: "김천시", dependency: 15 },
      { text: "문경시", dependency: 15 },
      { text: "봉화군", dependency: 15 },
      { text: "상주시", dependency: 15 },
      { text: "성주군", dependency: 15 },
      { text: "안동시", dependency: 15 },
      { text: "영덕군", dependency: 15 },
      { text: "영양군", dependency: 15 },
      { text: "영주시", dependency: 15 },
      { text: "영천시", dependency: 15 },
      { text: "예천군", dependency: 15 },
      { text: "울릉군", dependency: 15 },
      { text: "울진군", dependency: 15 },
      { text: "의성군", dependency: 15 },
      { text: "청도군", dependency: 15 },
      { text: "청송군", dependency: 15 },
      { text: "칠곡군", dependency: 15 },
      { text: "포항시", dependency: 15 },
      { text: "전체", dependency: 16 },
      { text: "거제시", dependency: 16 },
      { text: "거창군", dependency: 16 },
      { text: "고성군", dependency: 16 },
      { text: "김해시", dependency: 16 },
      { text: "남해군", dependency: 16 },
      { text: "밀양시", dependency: 16 },
      { text: "사천시", dependency: 16 },
      { text: "산청군", dependency: 16 },
      { text: "양산시", dependency: 16 },
      { text: "의령군", dependency: 16 },
      { text: "진주시", dependency: 16 },
      { text: "창녕군", dependency: 16 },
      { text: "창원시 마산합포회원구", dependency: 16 },
      { text: "창원시 의창성산구", dependency: 16 },
      { text: "창원시 진해구", dependency: 16 },
      { text: "통영시", dependency: 16 },
      { text: "하동군", dependency: 16 },
      { text: "함안군", dependency: 16 },
      { text: "함양군", dependency: 16 },
      { text: "합천군", dependency: 16 },
      { text: "전체", dependency: 17 },
      { text: "서귀포시", dependency: 17 },
      { text: "제주시", dependency: 17 },
      { text: "제주특별자치도", dependency: 17 },
    ]
  },
 
    type: "축종",
    kind: ["개", "고양이", "기타축종"],
  }),
  computed: {
    filteredData() {
      let options = this.options.opt_gugun
      return options.filter(o => o.dependency == this.support.home_sido)
    }
  }
};
</script>
